# Create a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data: |
{{- $baseProperties := (dict) }}
{{- include "test-chart.javaPropertiesToDict" (dict "result" $baseProperties "javaProperties" .Values.global.spring.config.base_a_properties) -}}
{{- $overriddenProperties := (dict) }}
{{- include "test-chart.javaPropertiesToDict" (dict "result" $overriddenProperties "javaProperties" .Values.spring.config.base_a_properties) -}}
{{- $mergedProperties := merge $overriddenProperties $baseProperties -}}
{{- range $key, $value := $mergedProperties }}
{{- printf "%s: %s" $key $value | nindent 4}}
{{- end }}
    # Delimiter
{{- include "test-chart.mergePropertiesV2" (dict "baseProperties" .Values.global.spring.config.base_a_properties "overriddenProperties" .Values.spring.config.base_a_properties) | nindent 4 -}}
    # Delimiter
{{- include "test-chart.mergePropertiesExtended" (list .Values.global.spring.config.base_a_properties .Values.spring.config.base_a_properties .Values.spring.extended_config.base_a_properties) | nindent 4 -}}
    # Delimiter
    foundValue: |
{{- include "test-chart.serachForValue" (dict "dictValues" .Values.global.spring.config "keyName" "base_a_properties") | nindent 6 -}}
    # Delimiter
{{- $foundValue := include "test-chart.serachForValue" (dict "dictValues" .Values.global.spring "keyName" "base_a_properties") | nindent 2 -}}
{{- printf "foundValue: | %s" $foundValue | nindent 4}}
    # Delimiter
{{- $foundValue = include "test-chart.serachForValue" (dict "dictValues" .Values.spring "keyName" "base_a_properties") | nindent 2 -}}
{{- printf "foundValue: | %s" $foundValue | nindent 4}}

