# Create a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data: |
{{- $baseProperties := (dict) }}
{{- include "test-chart.javaPropertiesToDict" (dict "result" $baseProperties "javaProperties" .Values.global.spring.config.base_a_properties) -}}
{{- $overriddenProperties := (dict) }}
{{- include "test-chart.javaPropertiesToDict" (dict "result" $overriddenProperties "javaProperties" .Values.spring.config.base_a_properties) -}}
{{- $mergedProperties := merge $overriddenProperties $baseProperties -}}
{{- range $key, $value := $mergedProperties }}
{{- printf "%s: %s" $key $value | nindent 4}}
{{- end }}
    # Delimiter
{{- $mergedProperties := (dict) }}
{{- include "test-chart.mergeProperties" (dict "result" $mergedProperties "baseProperties" .Values.global.spring.config.base_a_properties "overriddenProperties" .Values.spring.config.base_a_properties) -}}
{{/*{{- range $key, $value := $mergedProperties }}*/}}
{{/*{{- printf "%s: %s" $key $value | nindent 4}}*/}}
{{/*{{- end }}*/}}
{{/*{{- $mergedProperties := (dict) }}*/}}